import 'package:komik_app/models/enum.dart';
import 'package:komik_app/models/book_model.dart';

class Dummy {
  static List<BookModel> books = [
    BookModel(
      bookId: '01',
      imageUrl: 'assets/komik1.jpg',
      title: 'I Became the Tyrant of a Defense Game',
      rank: '67th, it has 5.7M views',
      alternative: 'Tyrant of the Tower Defense Game',
      author: 'Ha Jung,Ryueun Garam',
      artist: 'Gyong',
      genre: ' Action, Adventure, Fantasy, Isekai, Project',
      komik: Komik.manhwa,
      release: '2022',
      status: 'OnGoing',
      sinopsis:
          'RPG Tower Defense & Dungeon Attack \nAku Berhasil Menyelesaikan game yang belum pernah di selesaikan.\nAku tiba-ti pingsang dan terbangun di tempat yang tak dikenal\nTernyata aku, telah masuk ke dalam game sampah super sulit ini!\n“Aku akan menyelesaikan Game sampah ini apapun yang terjadi……!”',
    ),
    BookModel(
      bookId: '02',
      imageUrl: 'assets/komik2.jpg',
      title: 'Return Of The Mount Hua Sect',
      rank: '7th, it has 13.7M views',
      alternative: 'Return of the Blossoming Blade',
      author: 'Biga',
      artist: 'LICO',
      genre: 'Action, Comedy, Fantasy, Manhwa, Project, Shounen',
      komik: Komik.manhwa,
      release: '2021',
      status: 'OnGoing',
      sinopsis:
          'Chung Myung Murid ke-13 dari Mount hua sect, salah satu dari 3 swordsman terkuat, “Plum Blossom Sword Saint”, Mengalahkan Chun Ma, yang membawa kehancuran pada dunia ini. setelah pertarungan tersebut, ia menghembuskan nafas terakhirnya di atas gunung tempat mount hua sect berada. dia terlahir kembali 100 tahun kemudian di dalam tubuh seorang anak kecil.\n” …Apa”\n” Sekte Mount Hua telah hancur?”\n” Omong kosong macam apa itu!!?”',
    ),
    BookModel(
        bookId: '03',
        imageUrl: 'assets/komik3.jpg',
        title: 'Roguish Guard In A Medieval Fantasy',
        rank: 'N/A, it has 486.8K views',
        alternative: '중세 판타지 속 망나니 경비조장',
        author: 'Studio MW,Teddy Bear',
        artist: 'Kim Garden',
        genre: 'Action, Adventure, Drama, Fantasy, Historical, Project',
        komik: Komik.manhwa,
        release: '2024',
        status: 'OnGoing',
        sinopsis:
            '[2022 Grand Web Novel Contest Award-Winning Work]\nDi dunia abad pertengahan yang brutal dan tanpa adanya hukum yang berlaku,\nDimana perang, kemiskinan, sihir dan kegilaan merajalela.\nSang kepala penjaga tetap bertahan memaksakan dirinya sampai hari ini.'),
    BookModel(
      bookId: '04',
      imageUrl: 'assets/komik4.jpg',
      title: 'Return Of Frozen Player',
      rank: '13th, it has 12.2M views',
      alternative: '얼어붙은 플레이어의 귀환',
      author: 'JerryM',
      artist: 'SilSil',
      genre:
          'Action, Adventure, Fantasy, Magic, Manhwa, Project, Shounen, Violence',
      komik: Komik.manga,
      release: '2020',
      status: 'OnGoing',
      sinopsis: 'Pemain Beku',
    ),
    BookModel(
      bookId: '05',
      imageUrl: 'assets/komik5.jpg',
      title: 'Absolute Dominion',
      rank: 'N/A, it has 464.6K views',
      alternative: '절대군림',
      author: 'Younghoon Jang',
      artist: 'Park Shi-dae',
      genre: 'Action, Comedy, Fantasy, Martial Arts, Project',
      komik: Komik.manhwa,
      release: '2024',
      status: 'OnGoing',
      sinopsis:
          '“Aku akan melahap Jianghu ini!”\nUcapan seorang anak misterius dari pedagang buah, dengan Monarch Sword di tangan kirinya, dan Hell Blade di tangan kanannya.\nTidak hanya ahli bersilat lidah tapi juga memiliki kemampuan martial yang sangat hebat, apa yang menjadi tujuan utamanya?\nPerjalanan yang menyenangkan dari pemuda berusia 20 tahun, ‘Jeok Leegeon’, yang bermimpi untuk mendominasi dunia martial, dimulai!',
    ),
    BookModel(
      bookId: '06',
      imageUrl: 'assets/komik6.jpg',
      title: 'The World After The Fall',
      rank: '24th, it has 10M views',
      alternative:
          '멸망 이후의 세계 | The World After the End | The World After Destruction',
      author: 'S-Cynaan,Sing-Shong,싱숑',
      artist: 'S-Cynaan,Sing-Shong,싱숑',
      genre: 'Action, Adventure, Fantasy, Manhwa, Project',
      komik: Komik.manhwa,
      release: '2022',
      status: 'OnGoing',
      sinopsis:
          'Manusia tiba-tiba dipanggil untuk menjadi “Walkers”, dan mereka perlu menyelesaikan menara untuk menyelamatkan dunia.\nKemudian, “Regression Stone” ditemukan. sekarang Walkers bisa “kembali” ke masa lalu.\nDan perlahan-lahan… semua orang pergi. “Jika aku pergi ke masa lalu, lalu bagaimana dengan nasib orang-orang di dunia ini?\nSiapa yang akan menyelamatkan mereka?\nHarapan terakhir umat manusia, kelompok “Carpe Diem”,\ndibentuk oleh orang-orang yang menolak untuk meninggalkan dunia.\nTapi, begitu Walker terakhir mencapai lantai 100, dia tidak tahu lagi apa yg harus dia percayai.\nIni adalah kisah tentang satu-satunya pria yang ‘pantang mundur’ untuk meninggalkan dunianya, meskipun semua walker yang lain kembali ke masa lalu.',
    ),
    BookModel(
      bookId: '07',
      imageUrl: 'assets/komik7.jpg',
      title: 'Nano Machine',
      rank: '2nd, it has 22.7M views',
      alternative: '나노마신',
      author: 'Han-Joong-Wueol-Ya',
      artist: 'Guem-Gang-Bul-Gae',
      genre: 'Action, Adventure, Fantasy, Manhwa, Project',
      komik: Komik.manhwa,
      release: '2020',
      status: 'OnGoing',
      sinopsis:
          'Setelah direndahkan dan menghabiskan hidupnya dalam bahaya, seorang yatim piatu dari pemuja iblis, Yeo-Woon, mendapatkan kunjungan tak terduga dari keturunannya dari masa depan yang memasukkan sebuah mesin nano ke dalam tubuh Cheon-Woon, yang mengubah hidup Cheon Yeo Woon setelah aktivasi. Ikuti Cerita tentang perjalanan Cheon Yeo-Woon di reaperscans.id, melewati pemujaan setan dan naik menjadi yang ahli beladiri terbaik baru saja dimulai.',
    ),
    BookModel(
      bookId: '08',
      imageUrl: 'assets/komik8.jpg',
      title: 'The Return of The Disaster Class Hero',
      rank: '63rd, it has 5.9M views',
      alternative: '재앙급 영웅님이 귀환하셨다',
      author: 'HEATS,SAN.G (산지직송)',
      artist: 'BGman,Redice Studio',
      genre:
          'Action, Adventure, Comedy, Isekai, Manhwa, Project, Revenge, Shounen',
      komik: Komik.manhwa,
      release: '2022',
      status: 'OnGoing',
      sinopsis:
          'Pernah ada seorang pahlawan yang dianggap terkuat di Bumi. “Tapi dia sudah mati. Bagaimana mungkin seseorang yang kita bunuh bisa hidup kembali?” “Ya. aku juga ingin melihatnya jika dia bisa hidup kembali.” Namun, 20 tahun kemudian, dia benar-benar kembali! ”Kenapa kalian begitu terkejut? Apakah kalian melakukan sesuatu yang membuat kalian merasa bersalah?” ”Bajingan-bajingan ini. Aku tidak akan membiarkan mereka begitu saja.”',
    ),
    BookModel(
      bookId: '09',
      imageUrl: 'assets/komik9.jpg',
      title: 'Pick Me Up',
      rank: '14th, it has 12.1M views',
      alternative: ' Pick Me Up, Infinite Gacha',
      author: 'Hermod (헤르모드),U-Ne Cho (조우네)',
      artist: 'Redice Studio,Wasakbasak',
      genre: 'Action, Adventure, Comedy, Fantasy, Project',
      komik: Komik.manhwa,
      release: '2022',
      status: 'OnGoing',
      sinopsis:
          'Dalam game gacha yang terkenal dengan kesulitannya yang mengerikan, Master peringkat ke-5 di dunia, ‘Loki’, kehilangan kesadaran saat menyerbu Dungeon.\n“Apa? Aku karakter game sekarang?”\nSetelah bangun, “Loki” menyadari bahwa dia telah berubah menjadi Pahlawan Level 1, Bintang 1—“Han Yslat”. Untuk kembali ke Bumi, dia harus memimpin para master dan hero pemula dan membersihkan lantai 100 Dungeon!\n“Kau macam-macam dengan orang yang salah”\nIni adalah kisah perjuangan keras Master Loki yang belum pernah mengalami satu kekalahan pun.',
    ),
    BookModel(
      bookId: '10',
      imageUrl: 'assets/komik10.jpg',
      title: 'Solo Leveling : Ragnarok',
      rank: 'N/A, it has 3.2M views',
      alternative: '나 혼자만 레벨업 : 라그나로크',
      author: 'Updating',
      artist: 'Updating',
      genre: 'Action, Adventure, Fantasy, Project',
      komik: Komik.manhwa,
      release: '2024',
      status: 'OnGoing',
      sinopsis:
          'Keberadaan Bumi sekali lagi mendapatkan ancaman ketika Itarim, gods dari universe lain, ingin mengisi kekosongan yang ditinggalkan oleh Absolute Being. Sung Jinwoo tidak memiliki pilihan selain mengirimkan Beru, sang Shadow Ant King, untuk membangkitkan kekuatan anaknya dan membawanya menuju jalan yang dulu pernah dia tempuh. Suho harus menaklukkan Shadow Dungeon dan mendapatkan posisinya di dunia Hunter selagi dia menjalani dunia yang baru, melawan kejahatan baru yang berusaha melahap seisi dunia.',
    ),
    BookModel(
      bookId: '11',
      imageUrl: 'assets/komik11.jpg',
      title: 'Star-Embracing Swordmaster',
      rank: '61st, it has 6M views',
      alternative: 'Updating',
      author: 'Hong Dae-Wui,Q10',
      artist: 'Juno',
      genre: 'Action, Adventure, Fantasy, Project',
      komik: Komik.manhwa,
      release: '2023',
      status: 'OnGoing',
      sinopsis:
          'Vlad adalah anak gelandangan dari daerah kumuh yang selalu mengagumi kesatria.\nSetelah sebuah insiden di mana dia tersambar petir hitam, dia mulai mendengar suara.\nSuatu hari mendadak kesatria blue moonlight muncul, dan kehidupan Vlad di daerah kumuh itu berubah drastis…\nBahkan sebuah bintang yang redup yang tidak bersinar di puncak langit malam masih sebuah bintang jika ia ingin bersinar.',
    ),
    BookModel(
      bookId: '12',
      imageUrl: 'assets/komik12.jpg',
      title: 'The Villain Of Destiny',
      rank: '4th, it has 15.8M views',
      alternative: 'I Am The Fated Villain',
      author: '天命反派',
      artist: '绘术动漫',
      genre: 'Action, Adventure, Demon, Drama, Martial Arts, Project',
      komik: Komik.manhua,
      release: 'Updating',
      status: 'OnGoing',
      sinopsis:
          'Begitu Gu Changge menyadari dia telah masuk ke sebuah dunia fantasi, protagonis dunia itu yang dengan beruntungnya terpilih, bersumpah untuk melakukan balas dendam terhadapnya. Semua orang sangat iri pada Protagonis itu, karena bukan hanya karakter utama wanita tergila-gila padanya, tapi dia juga selalu diperlakukan sebagai tamu kehormatan kemanapun dia pergi. Untungnya, martabat dan kekuatan Gu Changge jauh melebihi milik orang lain, sehingga dia tidak dengan mudah jatuh di tangan orang yang hanya terpilih karena keberuntungannya?\nTunggu dulu… ada sistem yang didedikasikan untuk meraup dan mengambil dari apa yang dimiliki protagonis? Gu Changge tersenyum. “Sepertinya takdir pun ingin aku memenuhi takdirku sebagai orang jahat di dunia ini!”',
    ),
    BookModel(
      bookId: '13',
      imageUrl: 'assets/komik13.jpg',
      title: 'Omniscient Reader’s Viewpoint',
      rank: '6th, it has 14.6M views',
      alternative: 'Prespektif Pembaca Mahatahu | 전지적 독자 시점',
      author: 'Sing N Song',
      artist: 'Sleepy-C,UMI',
      genre:
          'Action, Adventure, Demon, Fantasy, Manhwa, Project, Psychological, Shounen',
      komik: Komik.manhwa,
      release: '2020',
      status: 'OnGoing',
      sinopsis:
          'Kim Dokja adalah pekerja kantoran biasa yang minat satu-satunya adalah membaca novel web favoritnya ‘Tiga Cara untuk Bertahan dari Kiamat.’ Tetapi ketika novel itu tiba-tiba menjadi kenyataan, dia adalah satu-satunya orang yang tahu bagaimana dunia akan berakhir. Berbekal hal tersebut, Dokja menggunakan pemahamannya untuk mengubah jalannya cerita, dan dunia, seperti yang dia tahu.',
    ),
    BookModel(
      bookId: '14',
      imageUrl: 'assets/komik14.png',
      title: 'The Regressed Mercenary’s Machinations',
      rank: 'N/A, it has 508.2K views',
      alternative: '회귀한 용병은 다 계획이 있다',
      author: 'Updating',
      artist: 'Updating',
      genre: 'Action, Adventure, Fantasy, Project',
      komik: Komik.manhwa,
      release: '2024',
      status: 'OnGoing',
      sinopsis:
          'Ghislain Perdium, sang Mercenary King dan salah satu orang terkuat di benua, memulai perang untuk membalaskan dendam keluarganya.\nRencana balas dendamnya berjalan dengan lancar sampai dia dihabisi oleh Idun, yang tidak disangka-sangka malah muncul. Ghislain mengira bahwa dia sudah mati, namun kembali bangun sebagai dirinya yang masih muda sebelum keluarganya runtuh.\nDengan kesempatan kedua ini, dia memutuskan untuk memperbaiki semua kepingan puzzle yang salah dan menghindari kesalahan-kesalahan di kehidupan sebelumnya!',
    ),
    BookModel(
      bookId: '15',
      imageUrl: 'assets/komik15.jpg',
      title: 'The Hero Became The Duke’s Eldest Son',
      rank: 'N/A, it has 2.6M views',
      alternative: '영웅, 공작가 장남 되다',
      author: 'Geulimjassi,Namukkun',
      artist: 'Jjumsaeng',
      genre: 'Action, Adventure, Fantasy, Project',
      komik: Komik.manhwa,
      release: '2024',
      status: 'OnGoing',
      sinopsis:
          'Aden Albireo dijuluki “Dragon Slayer,” pahlawan yang membunuh Berserker, dan Raja Iblis.\nYang pada akhirnya menyelamatkan dunia.\nTapi dia dikhianati oleh orang-orang yang dekatnya.\n“Aku tidak pernah berpikir akan hidup kembali!”\n15 tahun sebelum kebangkitan Raja Iblis,\nPutra sulung Duke yang ceroboh, yang tidak pernah terdengar dan tidak terlihat,\n“Aden Albireo” telah kembali dalam tubuh “Aden Remes”!\nTerlebih lagi…\n“Lama tidak bertemu, Dragon King!”\nRaja Iblis yang kupikir telah kubunuh ada di dalam jiwaku?!',
    ),
    BookModel(
      bookId: '16',
      imageUrl: 'assets/komik16.jpg',
      title: 'Legend Of Heavenly Chaos Demon',
      rank: 'N/A, it has 3.4M views',
      alternative:
          '괴력 난신, Myst, Might, Mayhem, The Chaotic God of Extraordinary Strength',
      author: 'Hanjoong Wolya',
      artist: 'Redice Studio',
      genre: 'Action, Adventure, Fantasy, Project',
      komik: Komik.manhwa,
      release: '2024',
      status: 'OnGoing',
      sinopsis:
          '[Dari studio yang banyak membawakan komik favorit kalian, <REDICE>, dan penulis yang membawakan <Nano Machine> dan <Absolute Sword Sense!>\nJeong, sang Slaughtering Scythe Demon, merasakan kesenangan dalam membunuh orang lain.\nDia kebetulan terlihat seperti Mok Gyeongwoon, Tuan Muda Ketiga dari Mok Sword Manor…\n“Kalau kau ingin berpura-pura menjadi diriku dan menjalani hidupku, aku akan mengeluarkanmu dari penjara ini.”\n“Apa kau sungguh akan memberikan aku kesempatan itu?”\n“Ahhh-!!!”\nDia membunuh Tuan Muda Ketiga dan menjalani hidupnya berpura-pura menjad dirinya.\nApakah Mok Gyeongwoon yang palsu akan bertahan di kehidupan ini?\nSang pembunuh berantai memulai hidupnya sebagai Tuan Muda Ketiga dari Mok Sword Manor yang hebat.\nINPO!!\n<Legend Of Heavenly Chaos Demon> terjadi 800 Tahun lalu sebelum Cheon Yeo Woon, Nano Machine.\nDan.. Soh Woonhwi <Absolute Sword Sense> terjadi 1000 Tahun lalu sebelum Cheon Yeo Woon, Nano Machine.',
    ),
    BookModel(
      bookId: '17',
      imageUrl: 'assets/komik17.jpg',
      title: 'SuperHuman Battlefield',
      rank: '12th, it has 12.7M views',
      alternative: ' 초인의 게임',
      author: 'Nicollo,Zero Two',
      artist: 'Plan A',
      genre: 'Action, Adventure, Fantasy, Project, Seinen, Sports',
      komik: Komik.manhwa,
      release: '2022',
      status: 'OnGoing',
      sinopsis:
          'Seo Moonyeob, pahlawan yang menyelamatkan umat manusia denga mengorbankan dirinya, superhuman terkuat.\nSaat dia tiba-tiba kembali ke dunia yang damai 17 tahun kemudian, yang telah menganggapnya mati.\ndunia sudah berubah, dan sekarang orang-orang bersaing dalam olahraga <Superhuman Battlefield\nWebtoon Menarik Fantasi  X sports X action!',
    ),
    BookModel(
      bookId: '18',
      imageUrl: 'assets/komik18.jpg',
      title: 'One Piece',
      rank: 'N/A, it has 2.8M views',
      alternative: 'Updating',
      author: 'Oda Eiichiro',
      artist: 'Updating',
      genre: 'Action, Adventure, Comedy, Drama, Fantasy, Mirror',
      komik: Komik.manga,
      release: '1997',
      status: 'OnGoing',
      sinopsis:
          'Bercerita tentang seorang laki-laki bernama Monkey D. Luffy, yang menentang arti dari gelar bajak laut. Daripada kesannama besar, kejahatan, kekerasan, dia lebih terlihat seperti bajak laut rendahan yang suka bersenang-senang, alasanLuffy menjadi bajak laut adalah tekadnya untuk berpetualang di lautan yang menyenangkan dan bertemu orang-orangbaru dan menarik, sertabersama-sama mencari One Piece.',
    ),
  ];
}
